### ISSUE TITLE
Test A+ Docker scripts with Docker Compose v2 and fix them

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1037]
A+ courses usually have the files docker-up.sh, docker-compose.yml and docker-compile.sh for local testing of the course and A+ in Docker containers. Docker Compose v2 was released in the autumn 2021 and it is not compatible with Compose v1. Test and fix the A+ Docker scripts so that they support the latest versions of Docker Compose and Docker Desktop for Mac (and Windows?).

From a teacher:

> This morning after updating docker desktop on a Windows I started to get the following error 

```
grader_1  | Internal Server Error: /default/aplus-json
grader_1  | Traceback (most recent call last):
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 34, in inner
grader_1  |     response = get_response(request)
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 115, in _get_response
grader_1  |     response = self.process_exception_by_middleware(e, request)
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 113, in _get_response
grader_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/aplus_auth/auth/django.py", line 61, in wrapper
grader_1  |     return func(request, *args, **kwargs)
grader_1  |   File "/srv/grader/util/auth.py", line 97, in wrapper
grader_1  |     return view_func(request, *args, course_key, **kwargs)
grader_1  |   File "/srv/grader/access/views.py", line 471, in aplus_json
grader_1  |     mf["children"] = children_recursion(m)
grader_1  |   File "/srv/grader/access/views.py", line 463, in children_recursion
grader_1  |     of["children"] = children_recursion(o)
grader_1  |   File "/srv/grader/access/views.py", line 456, in children_recursion
grader_1  |     _, exercise = config.exercise_entry(course["key"], str(of["key"]), '_root')
grader_1  |   File "/srv/grader/access/config.py", line 200, in exercise_entry
grader_1  |     exercise_root = self._exercise_root(course_root, exercise_key)
grader_1  |   File "/srv/grader/access/config.py", line 385, in _exercise_root
grader_1  |     data = self._process_exercise_data(course_root, data)
grader_1  |   File "/srv/grader/access/config.py", line 642, in _process_exercise_data
grader_1  |     default = recursion(data, default_lang, True)
grader_1  |   File "/srv/grader/access/config.py", line 633, in recursion
grader_1  |     v = self.TAG_PROCESSOR_DICT[tag](d, n, v, lang=lang)
grader_1  |   File "/srv/grader/access/config.py", line 102, in <lambda>
grader_1  |     'i18n': lambda root, parent, value, **kwargs: value.get(kwargs['lang']),
grader_1  | TypeError: unhashable type: 'list' 
```

I can't be sure now, but I think this error could be related to the Docker Compose changes.

**Comment by Mankro** [comment]
We can't test anything locally if the scripts do not work with Docker Compose v2. We can of course remove Docker Compose v2 and install v1, but that is only a temporary workaround.

**Comment by PasiSa** [comment]
My Windows + WSL2 just got updated to Docker Compose v2.12.2, and at least based on first tests aplus-manual seems to work ok
